export enum SLEvent {
  // react <-> electron
  MINIMIZE_WINDOW = 'MINIMIZE_WINDOW',
  MAXIMIZE_WINDOW = 'MAXIMIZE_WINDOW',
  CLOSE_WINDOW = 'CLOSE_WINDOW',
  WINDOW_MAXIMIZED = 'WINDOW_MAXIMIZED',
  WINDOW_UN_MAXIMIZED = 'WINDOW_UN_MAXIMIZED',
  SENT_FILE_ARGUMENTS = 'SENT_FILE_ARGUMENTS',

  // electron <-> database
  GET_DB_PATH = 'GET_DB_PATH',

  // database <-> react
  GET_DATABASE_HANDLER_CONTENTS_ID = 'GET_DATABASE_HANDLER_CONTENTS_ID',

  // fsHandler <-> react
  GET_FS_HANDLER_CONTENTS_ID = 'GET_FS_HANDLER_CONTENTS_ID',

  // react <-> fsHandler <-> electron
  GET_FILE_ARGUMENTS = 'GET_FILE_ARGUMENTS',
  GET_ADDITIONAL_FILE_ARGUMENTS = 'GET_ADDITIONAL_FILE_ARGUMENTS',
  GET_MAIN_WINDOW_CONTENTS_ID = 'GET_MAIN_WINDOW_CONTENTS_ID',

  // react <-> fsHandler
  LOAD_TAB_IMAGE = 'LOAD_TAB_IMAGE',
}
